[package]
name = "simplefetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
regex = "1.10.5"
chrono = {version = "0.4.38", features = ["clock"]}
argparse = "0.2.2"
