[package]
name = "simplefetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "3.0.0"
regex = "1.11.2"
chrono = {version = "0.4.42", features = ["clock"]}
argparse = "0.2.2"
